( FiCL softcore glossary generation -- 5sep18ap )
INCLUDE glosgen.f
NEWGLOS
MAKEGLOS softcore.fr
MAKEGLOS ifbrack.fr
MAKEGLOS prefix.fr
MAKEGLOS ficl.fr
MAKEGLOS jhlocal.fr
MAKEGLOS marker.fr
MAKEGLOS mini-oof.fs
MAKEGLOS ficllocal.fr
MAKEGLOS fileaccess.fr
MAKEGLOS header.fs
MAKEGLOS srcline.fs
MAKEGLOS tester.fr
MAKEGLOS toolbelt.fr
MAKEGLOS switch.fr
MAKEGLOS struct.fth
MAKEGLOS sfcompat.fs
MAKEGLOS bitwise.fs
MAKEGLOS circ-pad.fs
MAKEGLOS missing.fs
MAKEGLOS floats.fs
MAKEGLOS dshift.fs
MAKEGLOS cond.fs
MAKEGLOS systack.fs
MAKEGLOS strarray.fs
MAKEGLOS strconst.f
MAKEGLOS numcvt.fs
MAKEGLOS defer.fth
MAKEGLOS tofcompat.fs
MAKEGLOS words.fs
WRITEGLOS ficl.glo
